name: Notify Slack

on:
  push:
  pull_request:
    types: [opened, closed, reopened, synchronize]

jobs:
  notifySlack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Slack notification for push on main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          SLACK_MESSAGE: |
            :rocket: New commit pushed to `main` branch in `${{ github.repository }}`
            - *Branch:* `main`
            - *Commit:* `${{ github.sha }}`
            - *Author:* `${{ github.actor }}`
            - *Message:* `${{ github.event.head_commit.message }}`

      - name: Send Slack notification for push on other branches
        if: github.event_name == 'push' && github.ref != 'refs/heads/main'
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          SLACK_MESSAGE: |
            :rocket: New commit pushed to `${{ github.ref }}` in `${{ github.repository }}`
            - *Branch:* `${{ github.ref }}`
            - *Commit:* `${{ github.sha }}`
            - *Author:* `${{ github.actor }}`
            - *Message:* `${{ github.event.head_commit.message }}`

      - name: Send Slack notification for pull request on main
        if: github.event_name == 'pull_request' && github.base_ref == 'refs/heads/main'
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          SLACK_MESSAGE: |
            :rocket: Pull Request `${{ github.event.pull_request.title }}` targeting `main` branch by `${{ github.actor }}`
            - *Action:* `${{ github.event.action }}`
            - *PR URL:* `${{ github.event.pull_request.html_url }}`

      - name: Send Slack notification for pull request on other branches
        if: github.event_name == 'pull_request' && github.base_ref != 'refs/heads/main'
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
          SLACK_MESSAGE: |
            :rocket: Pull Request `${{ github.event.pull_request.title }}` targeting `${{ github.base_ref }}` by `${{ github.actor }}`
            - *Action:* `${{ github.event.action }}`
            - *PR URL:* `${{ github.event.pull_request.html_url }}`
